# Generated by Django 5.0.4 on 2024-04-07 16:46

import keyword_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keyword_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.CharField(
                max_length=40, validators=[keyword_app.validators.validate_name]
            ),
        ),
    ]
