# Generated by Django 5.0.4 on 2024-04-09 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("openai_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onet_name", models.CharField(max_length=150)),
                ("description", models.CharField()),
                ("tasks", models.JSONField(default=dict)),
                ("alt_names", models.JSONField(default=dict)),
                (
                    "occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="openai_app.occupation",
                    ),
                ),
            ],
        ),
    ]
