# Generated by Django 5.0.4 on 2024-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onet_app", "0004_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledge",
            name="description",
            field=models.JSONField(default=dict),
        ),
    ]
