name: Playwright Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Change directory to /front-end/
      run: cd front-end
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: front-end
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: front-end
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: front-end
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
